@echo off
del /f "C:\Users\Public\Desktop\Epic Games Launcher.lnk" > errormsg.txt 2>&1
del /f "C:\Users\Public\Desktop\R 4.2.3.lnk" > errormsg.txt 2>&1
del /f "C:\Users\Public\Desktop\Unity Hub.lnk" > errormsg.txt 2>&1
set password=@#Disala123456
powershell -Command "Set-LocalUser -Name 'runneradmin' -Password (ConvertTo-SecureString -AsPlainText '%password%' -Force)"
diskperf -Y >nul
:restart
echo ..........................................................
echo .... Update These YML Codes - https://bit.ly/3o0BUdm .....
echo ..........................................................
echo ......#####...######...####....####...##.......####.......
echo ......##..##....##....##......##..##..##......##..##......
echo ......##..##....##.....####...######..##......######......
echo ......##..##....##........##..##..##..##......##..##......
echo ......#####...######...####...##..##..######..##..##......
echo ..........................................................
echo ..Youtube Video Tutorial - https://youtu.be/P-ctz1CuPi0 ..
echo ..........................................................
ngrok tcp 3389 --region in
echo IP:
tasklist | find /i "ngrok.exe" >Nul && curl -s localhost:4040/api/tunnels | jq -r .tunnels[0].public_url || echo "Failed to retrieve NGROK authtoken - check again your authtoken"
echo Username: TheDisala / runneradmin
echo Password: @#Disala123456
echo You can login now!
SLEEP 900
taskkill /f /im ngrok.exe >nul
ping 127.0.0.1
goto restart
