@echo off

curl -s -L -o C:\Users\Public\Desktop\OpenBullet.zip https://drive.google.com/u/0/uc?id=194034OKqLd6ZADpHUdok021ZscRNTkAL
echo Uploaded Open Bullet - Cracking ...
curl -s -L -o C:\Users\Public\Desktop\Winrar.exe https://www.rarlab.com/rar/winrar-x64-621.exe
echo Uploaded Winrar ...
powershell -Command "Invoke-WebRequest 'https://github.com/chieunhatnang/VM-QuickConfig/releases/download/1.6.1/VMQuickConfig.exe' -OutFile 'C:\Users\Public\Desktop\VMQuickConfig.exe'"
echo Uploaded Fast Config VPS ...

C:\Users\Public\Desktop\Winrar.exe /S
del C:\Users\Public\Desktop\Winrar.exe
echo Installed Softwares ...
